#!/bin/bash

################################################################################

### Set bash environment error management

set -e
set -u

### Source local functions file

echo
source_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $source_dir/functions

### Check for root user runtime

check_root

### Download and source openspace functions file

download_os_functions
source_os_functions

################################################################################

### Actually run the installer

os-run_install
